export interface Tool {
  id: string;
  name: string;
  icon: string;
  color: string;
  description: string;
  categories: string[];
  features: string[];
  instruction?: string;
  examples?: string[];
}

export const tools: Tool[] = [
  {
    id: 'worksheet-generator',
    name: 'Worksheet Generator',
    icon: '⚡',
    color: 'purple',
    description: 'Create custom worksheets with practice problems tailored to your learning needs.',
    categories: ['Practice', 'Problem Solving'],
    features: ['Custom difficulty levels', 'Multiple subjects'],
    instruction: 'Enter the topic, subject, and difficulty level to generate a custom worksheet.',
    examples: ['Algebra worksheets for grade 9', 'Biology practice sheets', 'Grammar exercises'],
  },
  {
    id: 'multiple-choice-quiz',
    name: 'Multiple Choice Quiz',
    icon: '⚡',
    color: 'purple',
    description: 'Generate quizzes to test your knowledge on any subject.',
    categories: ['Practice', 'Study'],
    features: ['AI for grading', 'Timed tests'],
    instruction: 'Specify the topic and number of questions to create your quiz.',
    examples: ['World War II quiz', 'Chemistry periodic table quiz', 'Literature comprehension quiz'],
  },
  {
    id: 'math-problem-solver',
    name: 'Math Problem Solver',
    icon: '⚡',
    color: 'green',
    description: 'Get step-by-step solutions to math problems with detailed explanations.',
    categories: ['Problem Solving'],
    features: ['Step-by-step solutions', 'Multiple problems'],
    instruction: 'Type in your math problem and get detailed step-by-step solutions.',
    examples: ['x² + 5x + 6 = 0', '∫ x² dx from 0 to 5', 'Find the derivative of sin(x)cos(x)'],
  },
  {
    id: 'flashcard-generator',
    name: 'Flashcard Generator',
    icon: '⚡',
    color: 'pink',
    description: 'Generate flashcards to help you memorize key concepts and terms.',
    categories: ['Study'],
    features: ['Spaced repetition', 'Custom decks'],
    instruction: 'Enter terms and definitions to create your flashcard deck.',
    examples: ['Spanish vocabulary', 'Historical dates', 'Science formulas'],
  },
  {
    id: 'study-guide-creator',
    name: 'Study Guide Creator',
    icon: '⚡',
    color: 'blue',
    description: 'Create comprehensive study guides for your upcoming tests.',
    categories: ['Study'],
    features: ['Key concepts', 'Summaries'],
    instruction: 'Provide your notes or textbook chapters to generate a study guide.',
    examples: ['AP Biology final exam', 'History chapter 5-7', 'Chemistry midterm review'],
  },
  {
    id: 'text-summarizer',
    name: 'Text Summarizer',
    icon: '⚡',
    color: 'orange',
    description: 'Summarize long texts and documents into key points.',
    categories: ['Reading'],
    features: ['Bullet point summaries', 'Adjustable length'],
    instruction: 'Paste your text and specify the desired summary length.',
    examples: ['Article summary', 'Chapter summary', 'Document overview'],
  },
  {
    id: 'vocabulary-builder',
    name: 'Vocabulary Builder',
    icon: '⚡',
    color: 'teal',
    description: 'Learn new vocabulary words with definitions and example sentences.',
    categories: ['Language'],
    features: ['Word lists', 'Example sentences'],
    instruction: 'Enter vocabulary words or upload a text to extract new words.',
    examples: ['SAT vocabulary', 'Academic words', 'Technical terms'],
  },
  {
    id: 'practice-problems',
    name: 'Practice Problems',
    icon: '⚡',
    color: 'red',
    description: 'Generate practice problems for any subject to improve your skills.',
    categories: ['Practice'],
    features: ['Adaptive difficulty', 'Instant feedback'],
    instruction: 'Select your subject and topic to generate practice problems.',
    examples: ['Algebra problems', 'Physics practice', 'Chemistry equations'],
  },
  {
    id: 'essay-outline-generator',
    name: 'Essay Outline Generator',
    icon: '⚡',
    color: 'purple',
    description: 'Create structured outlines for your essays and research papers.',
    categories: ['Writing'],
    features: ['Thesis statement', 'Argument structure'],
    instruction: 'Provide your essay topic and main arguments to create an outline.',
    examples: ['Persuasive essay on climate change', 'Argumentative essay structure', 'Research paper outline'],
  },
  {
    id: 'concept-explainer',
    name: 'Concept Explainer',
    icon: '⚡',
    color: 'blue',
    description: 'Get clear explanations of complex concepts in simple terms.',
    categories: ['Learning'],
    features: ['Simple language', 'Visual aids'],
    instruction: 'Ask about any concept and receive a clear explanation.',
    examples: ['What is photosynthesis?', 'Explain quantum physics', 'How does DNA replication work?'],
  },
  {
    id: 'note-taker',
    name: 'Note Taker',
    icon: '⚡',
    color: 'orange',
    description: 'Convert your thoughts and lectures into organized notes.',
    categories: ['Study'],
    features: ['AI-assisted', 'Topic extraction'],
    instruction: 'Paste your raw notes or text to create organized notes.',
    examples: ['Lecture transcript', 'Meeting notes', 'Interview notes'],
  },
  {
    id: 'grammar-assistant',
    name: 'Grammar Assistant',
    icon: '⚡',
    color: 'green',
    description: 'Check and improve your grammar and writing style.',
    categories: ['Writing'],
    features: ['Real-time checking', 'Style suggestions'],
    instruction: 'Paste your text to check grammar, spelling, and style.',
    examples: ['Essay review', 'Email editing', 'Report proofreading'],
  },
  {
    id: 'text-translator',
    name: 'Text Translator',
    icon: '⚡',
    color: 'blue',
    description: 'Translate text between different languages.',
    categories: ['Language'],
    features: ['50+ languages', 'Context-aware'],
    instruction: 'Enter text and select target language for translation.',
    examples: ['English to Spanish', 'French to English', 'German to Japanese'],
  },
  {
    id: 'visual-creator',
    name: 'Visual Creator',
    icon: '⚡',
    color: 'pink',
    description: 'Create visual aids and diagrams for better understanding.',
    categories: ['Creative'],
    features: ['Mind maps', 'Flowcharts'],
    instruction: 'Describe the concept or process you want to visualize.',
    examples: ['Water cycle diagram', 'Mind map of cell structure', 'Process flowchart'],
  },
  {
    id: 'plagiarism-checker',
    name: 'Plagiarism Checker',
    icon: '⚡',
    color: 'red',
    description: 'Check your work for originality and proper citations.',
    categories: ['Writing'],
    features: ['Similarity detection', 'Citation checks'],
    instruction: 'Upload or paste your document to check for plagiarism.',
    examples: ['Research paper check', 'Essay originality', 'Assignment review'],
  },
  {
    id: 'reading-helper',
    name: 'Reading Helper',
    icon: '⚡',
    color: 'green',
    description: 'Improve reading comprehension with guided questions and analysis.',
    categories: ['Reading'],
    features: ['Comprehension questions', 'Theme analysis'],
    instruction: 'Upload your reading material to get comprehension questions.',
    examples: ['Novel analysis', 'Article questions', 'Poem analysis'],
  },
];

export const getToolById = (id: string): Tool | undefined => {
  return tools.find(tool => tool.id === id);
};

